### ISSUE TITLE
upload-gphotosが起動しない。

### ISSUE THREAD

**Issue by PEkyokutyo** [3846masa/upload-gphotos#103]
環境はUbuntu16.04.1
core2duoで32bitです。
nodeのバージョンはv6.9.0
npmのバージョンはv4.1.1
です。
ログは
hoge@hoge:~$ upload-gphotos
/usr/local/lib/node_modules/upload-gphotos/lib/Photo.js:83
      var _ref2 = (0, _co.wrap)(regeneratorRuntime.mark(function _callee() {
                                ^

ReferenceError: regeneratorRuntime is not defined
    at /usr/local/lib/node_modules/upload-gphotos/lib/Photo.js:83:33
    at /usr/local/lib/node_modules/upload-gphotos/lib/Photo.js:114:6
    at Object.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/Photo.js:278:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/Album.js:13:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/index.js:64:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
 net_radio_archive;
となっていました。

一応sudoでやったのが↓です。
hoge@hoge-pc:~$ sudo upload-gphotos
[sudo] hoge のパスワード:
/usr/local/lib/node_modules/upload-gphotos/lib/Photo.js:83
      var _ref2 = (0, _co.wrap)(regeneratorRuntime.mark(function _callee() {
                                ^

ReferenceError: regeneratorRuntime is not defined
    at /usr/local/lib/node_modules/upload-gphotos/lib/Photo.js:83:33
    at /usr/local/lib/node_modules/upload-gphotos/lib/Photo.js:114:6
    at Object.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/Photo.js:278:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/Album.js:13:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/index.js:64:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by 3846masa** [comment]
v1.3.0 がリリースされ次第，修正されます．

**Comment by PEkyokutyo** [comment]
無事に出来ました。ありがとうございました
