### ISSUE TITLE
Binary version won't work

### ISSUE THREAD

**Issue by yatra9** [3846masa/upload-gphotos#111]
Windows7で配布されているバイナリが起動しません。
```
C:\>upload-gphotos.exe
nexe.js:98637
      throw new Error(
      ^

Error: Problem reading log4js config { appenders: [ { type: 'stdout' } ], replaceConsole: false }. Error was "No such native module stdout" (Error: No such native module stdout
    at NativeModule.require (bootstrap_node.js:435:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at requireAppender (nexe.js:98735:22)
    at loadAppender (nexe.js:98751:38)
    at nexe.js:98571:7
    at Array.forEach (native)
    at configureAppenders (nexe.js:98570:18)
    at configureOnceOff (nexe.js:98631:7)
    at configure (nexe.js:98692:3))
    at configureOnceOff (nexe.js:98637:13)
    at configure (nexe.js:98692:3)
    at Object.__dirname.612../connect-logger (nexe.js:98830:1)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.3../index (nexe.js:470:15)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
    at nexe.js:1:505
    at NativeModule.compile (bootstrap_node.js:502:7)
```

**Comment by 3846masa** [comment]
動的 require するモジュールがあると nexe で動かなくなる問題ですね....
log4js もいつの間にか動的 require が組み込まれていたようです

代替の logger 系モジュールを検討しておきます
それまでは npm install して使う方法でお願いします．
