### ISSUE TITLE
Upload is not working

### ISSUE THREAD

**Issue by it-guru** [3846masa/upload-gphotos#113]
Using:
$ node -v
v7.4.0

upload-gphotos -u XXXX@googlemail.com -p XXXXX  screenshot001.jpg

I get this error:

```
TypeError: Cannot read property 'state' of undefined
    at GPhotos.<anonymous> (/home/hvogler/node_modules/upload-gphotos/lib/index.js:682:33)
    at Generator.next (<anonymous>)
    at onFulfilled (/home/hvogler/node_modules/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/home/hvogler/node_modules/upload-gphotos/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/hvogler/node_modules/upload-gphotos/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/hvogler/node_modules/upload-gphotos/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/hvogler/node_modules/upload-gphotos/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/hvogler/node_modules/upload-gphotos/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/hvogler/node_modules/upload-gphotos/node_modules/request-promise/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/hvogler/node_modules/upload-gphotos/node_modules/request-promise/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/hvogler/node_modules/upload-gphotos/node_modules/request-promise/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
 1: node::Abort() [node]
 2: 0x12dc6c9 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0xa96fa0 [node]
 5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 6: 0x3596e23063a7

```

I have add a debug output at ...
        var result = _jsonAsync2.default.parse(resultRes.body);
**console.log(result);**

And this returns:

{ errorMessage: 
   { reason: 'REQUEST_REJECTED',
     additionalInfo: { 'uploader_service.GoogleRupioAdditionalInfo': [Object] },
     upload_id: 'AEnB2UocKVAXjv6NMOWsRc4JM5X0Znn4gBiOOis1YD8uwF5c6BlF2XFHe1c4b4gHaHDm_f7DUO9QB7k_RTFCN8IRhdF59tFTaWoHaS20Gw6iyll9pnMVxrk' } }

Logon works correct - but upload will rejected with  "reason: 'REQUEST_REJECTED'".

**Comment by 3846masa** [comment]
Hmm, I want to get more info.
Change `console.log(result);` to `console.dir(result, { depth: null });` in your debug code, and send output, please.

**Comment by it-guru** [comment]
I don't have any ideas vor Debugging! - Is there a kind of trace-mode in nodejs to localize the problem?

**Comment by 3846masa** [comment]
VSCode has the debugging tool for Node.js. Please try it.

And, If upload-gphotos can't work on especially environments, please check login via browser first.
When logged-in, access `https://photos.google.com/` and check that `window.WIZ_global_data.SNlM0e` is available.

**Comment by Einstein2150** [comment]
Same error:

Error: Can't fetch GPhotos params.
    at GPhotos.<anonymous> (/usr/l
ocal/lib/node_modules/upload-gphot
os/lib/index.js:231:33)
    at Generator.next (<anonymous>
)   
    at onFulfilled (/usr/local/lib
/node_modules/upload-gphotos/node_
modules/co/index.js:65:19)
    at process._tickCallback (inte
rnal/process/next_tick.js:103:7)
Aborted

**Comment by 3846masa** [comment]
Please check login via browser first.
When logged-in, access `https://photos.google.com/` and check that `window.WIZ_global_data.SNlM0e` is available.
If available, please retry to run `upload-gphotos`.

**Comment by Einstein2150** [comment]
How can I check that? I log in to Google photos and typed after the URL window.WIZ_global...

All I got was a 404 not found.

**Comment by Einstein2150** [comment]
Oh. I checked upload now again and now it's working... 😉

**Comment by Einstein2150** [comment]
@it-guru: I found a old version of upload-gphotos under my home/lib/node_modules which is part of the $PATH. After renaming the folder the upload worked. 

Maybe it's a result of a NPR-Update without root-privilegs. In this case the installation results in the user-folder. The correct installation is located at /use/local/lib/node_modules.

Maybe it's a confusion which path locates the right version of upload-gphotos. Please check that!

**Comment by zodman** [comment]
it happend to me too the  error of params.

and it was because google block the logging i can fix with masa comments

**Comment by brendanbowidas** [comment]
I am having the same issue with "Can't fetch GPhotos params". I am using the node.js library and everything is working fine on my local machine, but when I deploy my app to Digital Ocean, I get this error. I logged in with my browser and `window.WIZ_global_data.SNlM0e` is available, so that is not the problem. This is only happening on my remote server. Anybody have any ideas how to fix?

**Comment by zodman** [comment]
@brendanbowidas  the trick  is login to https://photos.google.com using the IP of your digital ocean VPS.

You can use sshuttle to connect to digital ocean  and open the browser  with the remote ip.

https://github.com/apenwarr/sshuttle

I use it to solve the problem.

**Comment by 3846masa** [comment]
@brendanbowidas 
Google reject access from new IP.
So, if you run upload-gphotos, you should login with new IP at first.

**Comment by leovicio** [comment]
I tried to change the user agent as if it were the chrome
I get email from that unidentified device

**Comment by kristoff2016** [comment]
Anyone able to fix it ?

**Comment by zodman** [comment]
this comment as the solution https://github.com/3846masa/upload-gphotos/issues/113#issuecomment-277141489

**Comment by leovicio** [comment]
use this on the machine where the account is in trouble
https://accounts.google.com/b/0/DisplayUnlockCaptcha

**Comment by Guilty-King** [comment]
Thank you for all your help 
I got it working on my GCP instance but if Google blocks login for new device then I guess you can write a nodejs code and deploy it on heroku or openshift, right?
If there is a workaround please let me know
