### ISSUE TITLE
SMS verification isn't supported

### ISSUE THREAD

**Issue by pdupavillon** [3846masa/upload-gphotos#196]
Hi,
I'm using upload-photos on my local macbook with the macos binary from the latest release : 1.4.2 
`./upload-gphotos -u xxxxx -p xxxx img.jpg`
And everything is fine, but the same command line not working on my debian VPS (with the linux binary), even after login to my google account to prevent IP 'blocking' from google.

If you have any idea ?
`ERROR Error: Can't fetch GPhotos params.
    at /snapshot/home/travis/build/3846masa/upload-gphotos/lib/index.js:208:31
    at next (native)
    at onFulfilled (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
 1: node::Abort() [./upload-gphotos]
 2: 0x1052219 [./upload-gphotos]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [./upload-gphotos]
 4: 0x9a2e12 [./upload-gphotos]
 5: 0x9a348e [./upload-gphotos]
 6: 0x646f191092a7
Aborted
`

Thanks,
Paul

**Comment by 3846masa** [comment]
Sorry for late response.

I have no idea for resolving your issue. It works on my debian VPS.
So, please try to log in and upload photo once via browser on debian VPS before using `upload-gphotos`.
And, If you use binary version, please try npm package version ( `npm i -g upload-gphotos` )

**Comment by pdupavillon** [comment]
After debugging, 
It seems that the 'set-cookie' is missing from the response header of the login request,
causing the failure of the login process.

**Comment by 3846masa** [comment]
I checked new account, Error like you received caused.
However, after logging in and verifing account (like [that](https://i.imgur.com/JYEpwAK.png)) via browser, no Error caused.
Please try to log in via browser on VPS first.
I recommend using [dorowu/ubuntu-desktop-lxde-vnc](https://hub.docker.com/r/dorowu/ubuntu-desktop-lxde-vnc/) docker image to login via browser remotely.

**Comment by pdupavillon** [comment]
Thanks for you reply,
Unfortunately, after uploading successfully pictures with firefox through VNC,
I still have the same error with the command line  ...

**Comment by 3846masa** [comment]
Did you turned on "Allowing less secure apps to access your account"?
(https://support.google.com/accounts/answer/6010255)
Please check it.

**Comment by pdupavillon** [comment]
Yes, the "allow less secure apps" is turned on.
like I said before, the same account working well on my laptop, but not on my VPS for unknown reason ...

**Comment by 3846masa** [comment]
Umm... Sorry, I don't know how to fix it.....

**Comment by 4getit** [comment]
Hello,

I have the same problem here. I tried on two different accounts and the 'Allow less secure apps' is turned on. I'm on a headless VPS with no browser. Can you think of any workaround for this?

```
./upload-gphotos -u xxx@gmail.com -p yyy zzz.mp4
ERROR Error: Can't fetch GPhotos params.
    at /snapshot/home/travis/build/3846masa/upload-gphotos/lib/index.js:208:31
    at next (native)
    at onFulfilled (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/snapshot/home/travis/build/3846masa/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
 1: node::Abort() [./upload-gphotos]
 2: 0x1052219 [./upload-gphotos]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [./upload-gphotos]
 4: 0x9a2e12 [./upload-gphotos]
 5: 0x9a348e [./upload-gphotos]
 6: 0x15c03c5092a7
Aborted
```

**Comment by pdupavillon** [comment]
Hi,
Finally found a solution for this issue (did a quick fix to handle it #202)
**Requirement** : recovery phone number associated to your google account.

Use the cli to solve the SMS challenge : ./upload-gphotos -c -u xxx -p xxx
Permits to handle this step 1 : 
![step 1](http://imageshack.com/a/img924/9879/epMo2F.png)

After, the cli will ask you to enter the received pin to fill this step.
![step 2](http://imageshack.com/a/img924/5514/3wTEBN.png)

And basically, after this step, your account will be 'unlocked'.

Hope this help.

**Comment by neocryptek** [comment]
@3846masa it would be great if you could merge in #202 as I have the same problem on one of my hosts and the fix 2804e47ebb7fc428a168920357972285fe684639 looks small and self-contained maintenance wise. 

Please reconsider accepting the pull request! 

Thanks for the great CLI!

**Comment by 3846masa** [comment]
Sorry, @neocryptek.
I have no plan to merge #202 at moment.
First reason, I don't want to write code that I won't use ([Read here](https://github.com/3846masa/upload-gphotos/pull/202#issuecomment-302244515)).
Second reason, I cannot try #202 because I haven't an account that required SMS verification.

**Comment by pdupavillon** [comment]
@neocryptek, If you are still stuck, I can suggest you to clone my fork.
`git clone https://github.com/pdupavillon/upload-gphotos.git`
run the `yarn install && npm run build;pkg` command
then `node ./lib/cli.js -c -u xxx -p xxxx` (maybe run it twice, for some reason it's not working the first time ...)

As the SMS verification seems to be only a one shot verification, afterward you could only use the regular binary from the official repo and remove the clone from your server.

**Comment by cnritng** [comment]
Anyone having this problem when login in at a new place(such as a new vps like me),please just visit https://accounts.google.com/b/0/DisplayUnlockCaptcha
to unlock your account for login without any verification,for temporarily!

**Comment by marcus645** [comment]
Is there any permanent solution for this, so that i can run the script without google locking me out from my account (in cases where i use the script from my server which is different location then mine) ?

**Comment by ZaxonXP** [comment]
@pdupavillon I did what you mention, but it did not work
`yarn install

ERROR: [Errno 2] No such file or directory: 'install'`

Could you please add more steps how to use your version over the author one?

I would like to use it with the app password. Will this work?

Regards,
Piotr

**Comment by mpiffault** [comment]
It hasn't been specified here and I didn't try out, but maybe application password could resolve this issue : https://myaccount.google.com/apppasswords .
I'll give it a try and tell you.

**Comment by 3846masa** [comment]
`upload-gphotos@3.1.0` supports to load cookies from JSON file.
Please use this option.
