### ISSUE TITLE
Error when uploading large video file

### ISSUE THREAD

**Issue by cnritng** [3846masa/upload-gphotos#208]
try to uoload 16 video file(2.6-2.8GB each) using this script,but it gives me following error occasionally,

error output:
ERROR Server Error: sessionStatus is not found.
ERROR Error: Server Error: sessionStatus is not found.
    at /usr/lib/node_modules/upload-gphotos/lib/index.js:569:31
    at next (native)
    at onFulfilled (/usr/lib/node_modules/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
 1: node::Abort() [node]
 2: 0xdee5f9 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0x77411b [node]
 5: 0x77490e [node]
 6: 0x7822ae [node]
 7: 0x2fb3ccd092a7
Aborted

**Comment by jubilu** [comment]
Is there no way to upload files greater than 2 GB?

**Comment by 3846masa** [comment]
This is limitations of Google Photos.
Google Photos accept uploading up to 10GB per day, maybe.
See README.
