### ISSUE TITLE
Error when creating album named with only numbers

### ISSUE THREAD

**Issue by cnritng** [3846masa/upload-gphotos#214]
but I do remember it work before until this error occur,actually it create an album automatically.
this is the log,hope it will help!
INFO Uploaded successfully!
ERROR Album "20170611" is not found.
ERROR Failed to create album. Bad Request
ERROR Error: Bad Request
    at /usr/lib/node_modules/upload-gphotos/lib/index.js:477:31
    at next (native)
    at onFulfilled (/usr/lib/node_modules/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
 1: node::Abort() [node]
 2: 0xdee5f9 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0x77411b [node]
 5: 0x77490e [node]
 6: 0x7822ae [node]
 7: 0x32776ae092a7
Aborted

**Comment by 3846masa** [comment]
Sorry for the late reply.
Fixed on v1.4.3.
