### ISSUE TITLE
ERROR "Cannot read property 'state' of undefined"on windows7/10

### ISSUE THREAD

**Issue by cnrting** [3846masa/upload-gphotos#221]
INFO atParam is AKP94S2Rqa2ZIoWC8d91cKqwr1mGxI3lUA:1498938033896.
Uploading [=======================================================================================] 100% 0.0s

ERROR TypeError: Cannot read property 'state' of undefined
    at C:\snapshot\upload-gphotos\lib\index.js:603:31
    at next (native)
    at onFulfilled (C:\snapshot\upload-gphotos\node_modules\co\index.js:65:19)
    at tryCatcher (C:\snapshot\upload-gphotos\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (C:\snapshot\upload-gphotos\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\upload-gphotos\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\upload-gphotos\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\upload-gphotos\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\snapshot\upload-gphotos\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\snapshot\upload-gphotos\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.e.Async.drainQueues (C:\snapshot\upload-gphotos\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

upload file type:mkv video file

**Comment by 3846masa** [comment]
Hmm... I have no idea why causing error...

Please check below and report to me.
- Try to upload other `.mkv` file
- Try to upload `.mp4` file which converted from original
- Try to upload small video file (if you will upload fuge file)
- Try to upload via Web browser (Is your file supported by Google Photos?)
- Check your video format via `ffprobe`

**Comment by cnritng** [comment]
@3846masa I have sucessfully upload a 5GB mkv file to Google photos via the upload-gphotos linux client,so it might not be the size problem,and I can use firefox and chrome to upload the  same mkv video suceessfully which failed on upload-gphotos windows client.
