### ISSUE TITLE
JSON Error when uploaded

### ISSUE THREAD

**Issue by ManuCart** [3846masa/upload-gphotos#229]
Hi, 
I often have errors like that
````
ERROR SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.parse (/usr/local/lib/node_modules/upload-gphotos/lib/utils/json-async.js:8:17)
    at /usr/local/lib/node_modules/upload-gphotos/lib/index.js:602:42
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
````
What does it mean?

**Comment by 3846masa** [comment]
This error caused [here](https://github.com/3846masa/upload-gphotos/blob/2a06ad4a80b85c9bf0ef8987f510b669b8ec0e8d/src/index.js#L463).
However, I never seen this error yet. I don't know why caused.

**Comment by ManuCart** [comment]
New error today about gateway
````
ERROR Failed to fetch albums. Bad Gateway
ERROR Error: Bad Gateway
    at /usr/local/lib/node_modules/upload-gphotos/lib/index.js:477:31
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Aborted
````

**Comment by 3846masa** [comment]
`502 Bad Gateway` is server error.
It's caused on Google Photos server, I think.
Please retry later.

**Comment by ManuCart** [comment]
Yes,
First JSON error seem to be Google Photos server error too.
Today after 24h upload, not so much errors than yesterday.
Wait and see...

**Comment by 3846masa** [comment]
I catched `Unexpected end of JSON input` many times.
But, I tried to upload at most 3 times if failed, it succeed to upload within 3 times.
I think this error is Google Photos' error.

I'll implement a retry options for upload error.

**Comment by 3846masa** [comment]
Moved to https://github.com/3846masa/upload-gphotos/issues/233
