### ISSUE TITLE
 Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by ManuCart** [3846masa/upload-gphotos#235]
````
ERROR TypeError: Cannot read property 'state' of undefined
    at /usr/local/lib/node_modules/upload-gphotos/lib/index.js:603:31
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Aborted
````
Hi,

With this error, Can I know the photo with the error?

**Comment by 3846masa** [comment]
This caused [here](https://github.com/3846masa/upload-gphotos/blob/v1.4.4/src/index.js#L464).

**Note:**
I'll try to fix Upload Error on #233.
I think almost Upload Errors are Google Photo's Error.
If you failed to upload, please try again.
When same error caused continuously, please you report via issues.

**Comment by ManuCart** [comment]
I found the problem for this error,
I try many time to upload a 12500px by 9000px photo 
I found it's fail too on google photo site.
I read this ; 
https://support.google.com/photos/answer/6174018?hl=en&vid=0-1025738173526-1502398038850
and it's says photos can't exceed 75MB or 100 megapixels
My photo is 12500x9000 so 112,5 megapixels
Is it possible for you to add a test for this ?
Thanks

**Comment by 3846masa** [comment]
I'll research and add test for upload limit.
This issue moved to https://github.com/3846masa/upload-gphotos/issues/246
