### ISSUE TITLE
Error after updating v1.4.4

### ISSUE THREAD

**Issue by ManuCart** [3846masa/upload-gphotos#236]
````
sudo npm install -g upload-gphotos
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/upload-gphotos -> /usr/local/lib/node_modules/upload-gphotos/lib/cli.js
+ upload-gphotos@1.4.4
added 320 packages in 408.275s
````

````
/usr/local/lib/node_modules/upload-gphotos/node_modules/log4js/lib/configuration.js:37
        throw new Error(
        ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console',
       layout: { type: 'pattern', pattern: '%[%p%] %m' } } ] }) - must have a property "appenders" of type object.
    at tests.forEach (/usr/local/lib/node_modules/upload-gphotos/node_modules/log4js/lib/configuration.js:37:15)
    at Array.forEach (<anonymous>)
    at Configuration.throwExceptionIf (/usr/local/lib/node_modules/upload-gphotos/node_modules/log4js/lib/configuration.js:35:11)
    at new Configuration (/usr/local/lib/node_modules/upload-gphotos/node_modules/log4js/lib/configuration.js:190:10)
    at Object.configure (/usr/local/lib/node_modules/upload-gphotos/node_modules/log4js/lib/log4js.js:172:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/cli.js:28:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
````

**Comment by 3846masa** [comment]
Thanks for issue.
It's caused because of log4js update.
I fixed and released v1.4.5.
