### ISSUE TITLE
Server Error: sessionStatus is not found

### ISSUE THREAD

**Issue by jubilu** [3846masa/upload-gphotos#256]
Getting this error after uploading about 30 videos.

**Comment by movewho** [comment]
Me too, 
This is message:

> {"errorMessage":{"reason":"REQUEST_REJECTED","additionalInfo":{"uploader_service.GoogleRupioAdditionalInfo":{"completionInfo":{"status":"REJECTED","customerSpecificInfo":{"statusCode":67}},"requestRejectedInfo":{"reasonDescription":"agent_rejected"}}}

**Comment by cnritng** [comment]
+1
this is the error log,and it seems it's a google side upload limit perday cause it works again after about 24h.
INFO Success to login!
INFO UserID is 103325086594506300696.
INFO atParam is AECbvesZHlGQwtGVNUH4R1WxPOSf:1509984695759.
ERROR Server Error: sessionStatus is not found.
ERROR Error: Server Error: sessionStatus is not found.
    at /usr/lib/node_modules/upload-gphotos/lib/index.js:569:31
    at next (native)
    at onFulfilled (/usr/lib/node_modules/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
 1: node::Abort() [node]
 2: 0xdf14e9 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0x7752db [node]
 5: 0x775ace [node]
 6: 0x78346e [node]
 7: 0x19cc61b092a7

**Comment by movewho** [comment]
is there upload video/photo into googe photos using token?

**Comment by marcus645** [comment]
I received following error:
Failed to upload. Retry after 3 sec. Server Error: sessionStatus is not found.�[31mERROR�[39m Failed to upload. Retry after 3 sec. Server Error: sessionStatus is not found.�[31mERROR�[39m Failed to upload. Server Error: sessionStatus is not found.�[31mERROR�[39m Error: Server Error: sessionStatus is not found. at GPhotos. (/usr/lib/node_modules/upload-gphotos/lib/index.js:327:39) at next (native) at fulfilled (/usr/lib/node_modules/upload-gphotos/lib/index.js:4:58) at process._tickCallback (internal/process/next_tick.js:109:7)


Now that i looked into it, i found that the video is uploaded, but the script reports error....

**Comment by marcus645** [comment]
this file was rather big: 168 MB, so maybe it has something to do with that...

**Comment by marcus645** [comment]
I will report back if not working, seems to be fine for now with version 2.0.2  !

**Comment by marcus645** [comment]
Okay, so problem still there unfortunately, i think it has to do with the size, cause now again a file with 170MB stopped.  It should be some kind of timeout issue.

**Comment by marcus645** [comment]
Hmm today i tried agagin and this very same file was uploaded succesfully, so the problem wasn't the size then.

**Comment by marcus645** [comment]
Maybe it is that there is a timeout so it is indeed connected to the size. Now it stopped again with one file with 150MB. So some timeout issue idk...

**Comment by kukhanh92** [comment]
video than 500Mb will happening this situation. how to solve it ?

**Comment by movewho** [comment]
I tried many different ways, with large video, when uploading directly on the browser also refused to upload. But I noticed when uploading large video, google photos do not call api as usual, but call through the "blob" method, i'm inquiring about it.

And the problem of uploading a refusal is confusing between the cases:
- Upload is limited by google terms
- Upload large videos restricted

**Comment by fsarihan** [comment]
I am getting this error too.

I tried a lot of videos. Under 350 mb videos uploaded successfully.

**Comment by cnritng** [comment]
where did you found that?google does't seems to make this clear,btw,is it possible to use the google drive's backupandsync's api to do these upload thing?

**Comment by 3846masa** [comment]
I found that by try-and-error.
I have no plan to research "Backup and Sync", because researching that is high cost for me.

**Comment by movewho** [comment]
Dear,

Thanks your project. You tried your best!
