### ISSUE TITLE
Upload stop too often if i use it frequently

### ISSUE THREAD

**Issue by marcus645** [3846masa/upload-gphotos#259]
Hello, i tried everything:
- disabled captcha "unlockcaptcha"
- disabled high security login in gmail
- tried logging in with ip and then running script from that ip
Still every now and then the script stops and hangs and gmail stops the login process, in this way the script is not useful at all... unreliable.
Does anybody has any permanent solution, so that gmail accepts logins if i run the script let's say every 10 seconds?

**Comment by marcus645** [comment]
Hello, now i have following error:
Failed to upload. Retry after 3 sec. Server Error: sessionStatus is not found.[31mERROR[39m Failed to upload. Retry after 3 sec. Server Error: sessionStatus is not found.[31mERROR[39m Failed to upload. Server Error: sessionStatus is not found.[31mERROR[39m Error: Server Error: sessionStatus is not found. at GPhotos. (/usr/lib/node_modules/upload-gphotos/lib/index.js:327:39) at next (native) at fulfilled (/usr/lib/node_modules/upload-gphotos/lib/index.js:4:58) at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by 3846masa** [comment]
Hi @marcus645 .

This error is discussing on #256.
Please report the following points about your issue to #256.

- Error message
- File info (size, type, etc.) you want to upload.
- Can you upload via browser (Official Google Photos site) ?

**Comment by marcus645** [comment]
okay thank you i will report there, and try again etc
