### ISSUE TITLE
script is failing

### ISSUE THREAD

**Issue by marcus645** [3846masa/upload-gphotos#260]
Failed to add photo in album. Bad Request[31mERROR[39m Error: Bad Request at /usr/lib/node_modules/upload-gphotos/lib/index.js:477:31 at next (native) at onFulfilled (/usr/lib/node_modules/upload-gphotos/node_modules/co/index.js:65:19) at tryCatcher (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:693:18) at Async._drainQueue (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:133:16) at Async._drainQueues (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:143:10) at Immediate.Async.drainQueues (/usr/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14) at runCallback (timers.js:672:20) at tryOnImmediate (timers.js:645:5) at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by marcus645** [comment]
Problem was album being full video count reached 2000
