### ISSUE TITLE
Can't login because of cookiejar-support issue

### ISSUE THREAD

**Issue by fsarihan** [3846masa/upload-gphotos#273]
Hello everyone.

When i try to login, i am getting this error. I think when the post to https://accounts.google.com/signin/challenge/sl/password url, it return 302 status. But this 302 is not what we want. And when it try run fetchParams, return error.

This is my loginData:
```
{ Page: 'PasswordSeparationSignIn',
  gxf: 'AFoagUWNFrYyqaynFEfujpPl_ttbxWpFOw:1513272782849',
  ProfileInformation: '',
  SessionState: '',
  _utf8: '☃',
  bgresponse: 'js_disabled',
  Email: '*********@gmail.com',
  Passwd: '***************' }
```

And this is my loginRes's header:
```
{ status: 302,
  statusText: 'Moved Temporarily',
  headers:
   { 'content-type': 'text/html; charset=UTF-8',
     'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
     pragma: 'no-cache',
     expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
     date: 'Thu, 14 Dec 2017 17:33:03 GMT',
     location: 'https://support.google.com/accounts/answer/61416?hl=en',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     'content-length': '236',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-xss-protection': '1; mode=block',
     server: 'GSE',
     'set-cookie':
      [ 'GAPS=1:yUIw-8MHo8qX9CRH0_Lz_V7vlRq0mg:zjq3hKgqU25SNn96;Path=/;Expires=Sat, 14-Dec-2019 17:33:03 GMT;Secure;HttpOnly;Priority=HIGH' ],
     'alt-svc': 'hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"',
     connection: 'close' }}

```

**Comment by 3846masa** [comment]
Sorry, It was caused by `@3846masa/axios-cookiejar-support` bug.
I'll fix.

**Comment by 3846masa** [comment]
@fsarihan I fixed and released as v2.0.6. Please try it.

**Comment by fsarihan** [comment]
@3846masa 

```
(node:6984) UnhandledPromiseRejectionWarning: TypeError: GPhotos is not a constructor
    at C:\Users\Administrator\Desktop\gphoto\program.js:62:27
    at Server.processRequest (C:\Users\Administrator\Desktop\gphoto\program.js:68:5)
    at Server.emit (events.js:159:13)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
(node:6984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fsarihan** [comment]
@3846masa
```
(node:6984) UnhandledPromiseRejectionWarning: TypeError: GPhotos is not a constructor
    at C:\Users\Administrator\Desktop\gphoto\program.js:62:27
    at Server.processRequest (C:\Users\Administrator\Desktop\gphoto\program.js:68:5)
    at Server.emit (events.js:159:13)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
(node:6984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I added this code on index.js and problem solved.
`module.exports = GPhotos;`

**Comment by fsarihan** [comment]
Hello again :) 

Meet with my new error @3846masa 

```
Error: Server Error: sessionStatus is not found.
    at GPhotos.<anonymous> (C:\Users\Administrator\Desktop\gphoto\node_modules\upload-gphotos\lib\index.js:321:39)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\Desktop\gphoto\node_modules\upload-gphotos\lib\index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by 3846masa** [comment]
First, this library is for ESnext modules.
If you want to use as commonjs, please try below.

```js
const GPhotos = require('upload-gphotos').default;

(async () => {
  const gphotos = new GPhotos({ username: 'XXX', password: 'XXX' });
  await gphotos.login();

  const photo = await gphotos.upload(filePath);
  const album = await gphotos.searchOrCreateAlbum('TestAlbum');
  await album.addPhoto(photo);
})();
```

**Comment by 3846masa** [comment]
Second, `Server Error: sessionStatus is not found.` error was caused by various reason.
So, I have no idea how to resolve. FYI: https://github.com/3846masa/upload-gphotos/issues/256

**Comment by fsarihan** [comment]
```
'{"errorMessage":{"reason":"REQUEST_REJECTED","additionalInfo":{"uploader_service.GoogleRupioAdditionalInfo":{"completionInfo":{"status":"REJECTED","customerSpecificInfo":{"statusCode":67}},"requestRejectedInfo":{"reasonDescription":"agent_rejected"}}},"upload_id
":"AEnB2UrDvc1QinRa4sOh0wLm_mcfepJ6f_kysUV-YkQMBFU4HZflk1Nqo8Ivf0l0LJ1dHPOHyh0J8-2KwpPS3SywIYJ2OgXAKw"}}'
```

This is returned data. Have you any idea for the solution?

**Comment by 3846masa** [comment]
Most cases, the reason maybe...
- File size is very large
- Upload limit per day

Please try upload this file via browser's Google Photos.
If you cannot upload via browser, It's Google Photos limit.

**Comment by 3846masa** [comment]
If your issue is only `sessionStatus` error, please discuss on #256 for my convenience.
If you have more issues, please resend issue separately one by one.

I'll close this issue because login issue was solved.
