### ISSUE TITLE
TypeError: client.abort is not a function

### ISSUE THREAD

**Issue by 3846masa** [3846masa/upload-gphotos#291]
```
TypeError: client.abort is not a function
    at XMLHttpRequest.abort (/app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:376:16)
    at Object.abort (/app/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:422:13)
    at RequestManager.close (/app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:131:21)
    at Window.close (/app/node_modules/jsdom/lib/jsdom/browser/Window.js:465:29)
    at GPhotos.<anonymous> (/app/node_modules/upload-gphotos/lib/index.js:175:20)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/upload-gphotos/lib/index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by 3846masa** [comment]
I'll replace "JSDOM" to "cheerio and esprima".
