### ISSUE TITLE
Failed to create album

### ISSUE THREAD

**Issue by ManuCart** [3846masa/upload-gphotos#297]
With CLI mode it's impossible to create an album name
The system upload first photo correctly and after that error :  
```
ERROR Failed to create album. Cannot read property 'id' of undefined
ERROR TypeError: Cannot read property 'id' of undefined
    at GPhotos.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/index.js:232:41)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/upload-gphotos/lib/index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
It's happen only for new album creation

**Comment by ManuCart** [comment]
Hi,
After tests, the error exist only with an old account came from picasa.
I create a new google account and everything work fine.
