### ISSUE TITLE
`page.waitForNavigation` timeout

### ISSUE THREAD

**Issue by tamdao** [3846masa/upload-gphotos#328]
I have tried to use new version. But I can't login with my account. I alway got TimeoutError

Error log

```
error { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/tamdao/Documents/home/freelancer/.../node_modules/puppeteer-core/lib/FrameManager.js:1276:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (/Users/tamdao/Documents/home/freelancer/.../node_modules/puppeteer-core/lib/helper.js:144:27)
    at Page.waitForNavigation (/Users/tamdao/Documents/home/freelancer/.../node_modules/puppeteer-core/lib/Page.js:644:49)
    at Page.<anonymous> (/Users/tamdao/Documents/home/freelancer/.../node_modules/puppeteer-core/lib/helper.js:145:23)
    at GPhotos.<anonymous> (/Users/tamdao/Documents/home/freelancer/.../node_modules/upload-gphotos/lib/index.js:137:37)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tamdao/Documents/home/freelancer/.../node_modules/upload-gphotos/lib/index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'TimeoutError' }
^C
```
I hava tried set  `timeout: 0` here `page.waitForNavigation({ timeout: 0, waitUntil: 'networkidle2' })`. But look like not work. The func stuck here

**Comment by 3846masa** [comment]
`page.waitForNavigation` sometimes cannot detect navigation.
I don't know how to fix. I'll research.

**Comment by tamdao** [comment]
Thanks for your help. I'll research

**Comment by 3846masa** [comment]
Try to replace `page.waitForNavigation(...)` to 
```
page.waitForRequest((request) => request.url().includes('/CheckCookie'))
```

**Comment by tamdao** [comment]
Got the same
```
error { TimeoutError: Timeout exceeded while waiting for event
    at Timeout.setTimeout (/Users/tamdao/Documents/home/freelancer/vlhaven_server/node_modules/puppeteer-core/lib/helper.js:242:24)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
  -- ASYNC --
    at Page.<anonymous> (/Users/tamdao/Documents/home/freelancer/vlhaven_server/node_modules/puppeteer-core/lib/helper.js:144:27)
    at GPhotos.<anonymous> (/Users/tamdao/Documents/home/freelancer/vlhaven_server/node_modules/upload-gphotos/lib/index.js:137:37)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tamdao/Documents/home/freelancer/vlhaven_server/node_modules/upload-gphotos/lib/index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'TimeoutError' }
```

**Comment by 3846masa** [comment]
Please tell me your environment

- Node version
- Chrome version
- OS

**Comment by tamdao** [comment]
- Node v9.2
- Chrome 71.0.3578.98
- Mac OS

**Comment by 3846masa** [comment]
Please try it.
`page.waitForRequest(...)` -> `page.waitFor(3000)`

(but, I avoid to use `waitFor` because of network delay :( )

**Comment by tamdao** [comment]
Ok. I debug the issue. :D

**Comment by tamdao** [comment]
Worked now :D. I will create a PR

**Comment by tamdao** [comment]
Please take a look my PR: https://github.com/3846masa/upload-gphotos/pull/329

Thanks for your help

**Comment by tamdao** [comment]
I have tried with small file and it worked. But not work with large file. I got the error log
```
error Error: Server Error: sessionStatus is not found.
0|index  |     at GPhotos.<anonymous> (/root/.../node_modules/upload-gphotos/lib/index.js:323:39)
0|index  |     at Generator.next (<anonymous>)
0|index  |     at fulfilled (/root/.../node_modules/upload-gphotos/lib/index.js:4:58)
0|index  |     at <anonymous>
0|index  |     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by 3846masa** [comment]
Large file is not support currently.
Please create new issue.

**Comment by tamdao** [comment]
@3846masa Thanks for your response. So I have a q: How can I implement the feature? Can you guide me? I think I can implement if I know the request flow for large file

**Comment by tamdao** [comment]
This issue resolved
