### ISSUE TITLE
LOGIN with browser cookie

### ISSUE THREAD

**Issue by kangdulba** [3846masa/upload-gphotos#341]
I think, it's better to log in using a browser cookie, so we are not blocked if Google updates on their login page.
so we just need to take the browser cookie using ext "edit this cookie" for chrome for example.

maybe this can be considered for the next update

**Comment by 3846masa** [comment]
`upload-gphotos@3.1.0` supports EditThisCookie exported JSON.

**Comment by samnangcattor** [comment]
i use upload-gphotos@3.1.0 but i got this 
ERROR RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Cookie.toJSON (/usr/local/lib/node_modules/upload-gphotos/node_modules/tough-cookie/lib/cookie.js:784:35)
    at JSON.stringify (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/util/parseEditThisCookieJSON.js:29:46)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/upload-gphotos/lib/util/parseEditThisCookieJSON.js:4:58)
 1: 0x7f810a88e46c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7f810a92c73d  [/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7f810ab422da v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7f810ab427f0  [/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7f810ab434ca  [/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x2aa12755452b 
[1]    23488 abort (core dumped)  upload-gphotos test.mp4 -c cookie.json
