### ISSUE TITLE
ファイル名に日本語を含む動画ファイルのアップロード

### ISSUE THREAD

**Issue by tmp0116** [3846masa/upload-gphotos#354]
Windowsにてupload-gphotos-win.exeを使用させていただいております。
v2.0.13では問題なく使用しておりましたが、
ログインの関係でv3.0.5に更新しましたところ
日本語を含むファイル名の動画ファイルをアップロードした際に
「Failed to upload. Retry after 3 sec. The header content contains invalid characters」
のエラーが発生しアップロードに失敗する状況です。
ヘッダのX-Goog-Upload-File-Nameに非ASCII文字が含まれてしまうことが原因ではないかと思うのですが、
その場合ファイル名をエンコードするなどの対応をしていただくことは可能でしょうか。
よろしくお願いいたします。

**Comment by 3846masa** [comment]
状況を調査するために、次の情報をください

- アップロードしたファイル名
- アップロードしたファイルの種類（.jpg / .png / .mp4 etc.）
- アップロードしたファイルのサイズ

**Comment by tmp0116** [comment]
・201905112150-テスト.mp4
・.mp4
・3.12GB

上記ファイルのファイル名を「201905112150-test.mp4」に変更するとエラーなく
アップロードされることを確認しました。
エラーのログは以下の通りです。
[91mERROR[39m Failed to upload. Retry after 3 sec. The header content contains invalid characters
[91mERROR[39m Failed to upload. Retry after 3 sec. The header content contains invalid characters
[91mERROR[39m Failed to upload. The header content contains invalid characters
[91mERROR[39m TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:494:11)
    at ClientRequest.setHeader (_http_outgoing.js:498:3)
    at new ClientRequest (_http_client.js:173:14)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at Object.request (C:\snapshot\project\node_modules\agent-base\patch-core.js:23:20)
    at dispatchHttpRequest (C:\snapshot\project\node_modules\axios\lib\adapters\http.js:141:25)
    at new Promise (<anonymous>)
    at httpAdapter (C:\snapshot\project\node_modules\axios\lib\adapters\http.js:18:10)
    at dispatchRequest (C:\snapshot\project\node_modules\axios\lib\core\dispatchRequest.js:59:10)
 1: node::DecodeWrite
 2: v8::internal::wasm::SignatureMap::Find
 3: v8::internal::Builtins::CallableFor
 4: v8::internal::Builtins::CallableFor
 5: v8::internal::Builtins::CallableFor
 6: 000001DAADC843C1

**Comment by 3846masa** [comment]
v3.0.6 で修正されました
