### ISSUE TITLE
createAlbum not working

### ISSUE THREAD

**Issue by tamdao** [3846masa/upload-gphotos#467]
The error log:
```
(node:69000) UnhandledPromiseRejectionWarning: Error: Error batchexecute (error: 3, query: OXvT9d)
    at Requestor.sendBatchExecute (/<project_path>/node_modules/upload-gphotos/lib/Requestor.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by 3846masa** [comment]
Please share your code (or your command) to resolve.

**Comment by tamdao** [comment]
@3846masa Thanks for your response. It's very simple

```
const gphotos = new GPhotos();
  await gphotos.signin({
    username,
    password
  });

const album =
            (await gphotos.searchAlbum({
              title: 'miruo_cos'
            })) ||
            (await gphotos.createAlbum({
              title: 'miruo_cos'
            }));
```

**Comment by 3846masa** [comment]
Is the version you use v4.2.0?
If you used v4.2.0, please try same code with v4.1.1.

**Comment by tamdao** [comment]
Checking

**Comment by tamdao** [comment]
v4.1.1: Work well

**Comment by 3846masa** [comment]
Ok, I see.
I'll revert the part of code from v4.1.1.

**Comment by 3846masa** [comment]
I'll release v4.2.1, try it.

**Comment by tamdao** [comment]
work well. Thanks :D
