### ISSUE TITLE
Error: Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.runtime'

### ISSUE THREAD

**Issue by book000** [3846masa/upload-gphotos#526]
The following error occurs when uploading.

```
upload-gphotos-win.exe "movie.mp4"
? Username? ********
? Password? [hidden]
          A plugin listed 'puppeteer-extra-plugin-stealth/evasions/chrome.runtime' as dependency,
          which is currently missing. Please install it:

          yarn add puppeteer-extra-plugin-stealth

          Note: You don't need to require the plugin yourself,
          unless you want to modify it's default settings.

Failed to login.
Error: Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.runtime'
Require stack:
- C:\snapshot\project\node_modules\puppeteer-extra\dist\index.cjs.js
- C:\snapshot\project\lib\puppeteer.js
- C:\snapshot\project\lib\signin_via_puppeteer.js
- C:\snapshot\project\lib\GPhotos.js
- C:\snapshot\project\lib\index.js
- C:\snapshot\project\lib\cli\index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at PuppeteerExtra.resolvePluginDependencies (C:\snapshot\project\node_modules\puppeteer-extra\dist\index.cjs.js:300:23)
    at PuppeteerExtra.launch (C:\snapshot\project\node_modules\puppeteer-extra\dist\index.cjs.js:118:14)
    at Object.signinViaPuppeteer (C:\snapshot\project\lib\signin_via_puppeteer.js:29:49)
    at GPhotos.signin (C:\snapshot\project\lib\GPhotos.js:26:42)
 1: 00007FF6AFED072F RC4_options+2829999
 2: 00007FF6AFE4DF36 RC4_options+2295478
 3: 00007FF6AFDC5539 RC4_options+1735865
 4: 00007FF6B0947150 RC4_options+13801680
 5: 00007FF6B0946377 RC4_options+13798135
 6: 00007FF6B0946808 RC4_options+13799304
 7: 00007FF6B09465DE RC4_options+13798750
 8: 00007FF6B0FD02DD RC4_options+20654685
 9: 00007FF6B0F4FD6C RC4_options+20129004
10: 00007FF6B0F9EE72 RC4_options+20452850
11: 00007FF6B0F6C90E RC4_options+20246670
12: 00007FF6B0F4D20C RC4_options+20117900
13: 00007FF6B0858F00 RC4_options+12826240
14: 00007FF6B0859123 RC4_options+12826787
15: 00007FF6B08595E2 RC4_options+12828002
16: 00007FF6B08319F5 RC4_options+12665205
17: 00007FF6B0947150 RC4_options+13801680
18: 00007FF6B0946377 RC4_options+13798135
19: 00007FF6B0946808 RC4_options+13799304
20: 00007FF6B09465DE RC4_options+13798750
21: 00007FF6B0FD02DD RC4_options+20654685
22: 00007FF6B0F4FD6C RC4_options+20129004
23: 00007FF6B0F4D321 RC4_options+20118177
24: 00007FF6B0F4CF0C RC4_options+20117132
25: 00007FF6B0858E73 RC4_options+12826099
26: 00007FF6B0858716 RC4_options+12824214
27: 00007FF6B098783B RC4_options+14065595
28: 00007FF6AFEF567D RC4_options+2981373
29: 00007FF6AFEF5A01 RC4_options+2982273
30: 00007FF6AFEEC9F3 RC4_options+2945395
31: 00007FF6AFD8D1B0 RC4_options+1505584
32: 00007FF6AFD8DBCC RC4_options+1508172
33: 00007FF6AFD039E2 RC4_options+942434
34: 00007FF6AFD03F68 RC4_options+943848
35: 00007FF6AFD06ED3 RC4_options+955987
36: 00007FF6AFD87645 RC4_options+1482181
37: 00007FF6AFF1342B RC4_options+3103659
38: 00007FF6AFF2DDDC RC4_options+3212636
39: 00007FF6AFF2E1D4 RC4_options+3213652
40: 00007FF6AFE01E52 RC4_options+1983954
41: 00007FF6AFE82CC3 RC4_options+2511939
42: 00007FF6AFCA10F1 RC4_options+538737
43: 00007FF6B10E11CC RC4_options+21772620
44: 00007FFA86B77BD4 BaseThreadInitThunk+20
45: 00007FFA882ACED1 RtlUserThreadStart+33
```

Running `yarn add puppeteer-extra-plugin-stealth` does not change the result.  
`node_modules\puppeteer-extra-plugin-stealth\evasions\chrome.runtime` existed.

The environment is as follows:

- OS: Windows 10 1903 (build 18362.657)
- upload-gphotos version: 4.2.1 (latest)

Thank you for developing this application.

**Comment by pag** [comment]
@3846masa Can you please provide a new release of the macos binary? I'm having the same problem and failing to install from npm or run from the source distribution.
