### ISSUE TITLE
Support gifs

### ISSUE THREAD

**Issue by Mattze96** [3846masa/upload-gphotos#91]
Hi,

when i have some gifs in my photo library and do fetchPhotoList i get the following error.

```
Unhandled rejection TypeError: Cannot read property '0' of undefined
    at upload-gphotos/lib/index.js:397:56
    at Array.map (native)
    at upload-gphotos/lib/index.js:387:36
    at Generator.next (<anonymous>)
    at onFulfilled (/node_modules/co/index.js:65:19)
```

**Comment by 3846masa** [comment]
Fixed. Please use v1.1.1.
